version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-2221c92b-danielcalebe719-2b82.l.aivencloud.com
      - DB_PORT=25538
      - DB_DATABASE=defaultdb
      - DB_USERNAME=avnadmin
      - DB_PASSWORD=AVNS_MRgcH_4ZC0MTrUnxZpv

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: AVNS_MRgcH_4ZC0MTrUnxZpv
      MYSQL_DATABASE: avnadmin
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
